### ISSUE TITLE
Question about usage of api

### ISSUE THREAD

**Issue by Syhler** [itsdax/Runescape-Web-Walker-Engine#103] opened 2022-01-09 13:37 UTC
I'm trying to make use of your API in another bot. I am currently having trouble understanding what these varbits are for. What are they used for? is it something specific to Tribot? and how does the API take usage of this information?

I have tried figuring out what they are used for but have run out of ideas. So I figured i would ask here, hopes that okay

Code found [here](https://github.com/itsdax/Runescape-Web-Walker-Engine/blob/master/src/main/java/dax/api_lib/models/PlayerDetails.java)
```
List<IntPair> settings = Stream.of(10, 11, 17, 32, 63, 68, 71, 101, 111, 116, 131, 144, 145, 150, 165, 176,
            179, 212, 273, 299, 302, 307, 314, 335, 347, 351,
 365, 371, 387, 399, 425, 437, 440, 
482, 622, 655, 671, 705, 794, 810,
            869, 896, 964, 970, 1630, 1671, 1672)
.map(value -> new IntPair(value, Game.getSetting(value))).distinct().collect(Collectors.toList());

    List<IntPair> varbit = Arrays.stream(new int[]{
            192,
            199,
            357,
            2310,
            2328,
            3534,
            3741,
            4538,
            4566,
            4885,
            4895,
            4897,
            5087,
            5088,
            5089,
            5090,
            5810,
            6104,
            7255,
            9016
        })
                .mapToObj(value -> new IntPair(value, RSVarBit.get(value).getValue())).distinct().collect(
				        Collectors.toList());
```

**Comment by FALSkills** [comment] 2022-01-09 15:10
Hi,
RSVarBit and Game Settings are not unique to TRiBot, but the naming scheme likely is.  I believe that game settings are called "Varps" in Runelite/openosrs, and RSVarBits are called varbits.    They provide important information to the path generator that tells it which areas your account has access to.  If they are not passed along, many areas that are quest or region-locked will not be supported unless you are already within those areas.  An example would include: the path generator won't create a path to Lumbridge Swamp Caves unless you have placed the rope to enter the caves, which can be confirmed via one of those varbits.

**Comment by Syhler** [comment] 2022-01-09 16:02
Arghh I see! Thanks
I'm just getting into all this varpbit/varbit. Super confusing.
Is there anywhere I can look up these varpbit/varbit and see their usage?  Have tried using [this](https://oldschool.runescape.wiki/w/RuneScape:Varbit) with no luck.

Also, what is the expected value for a "account got access to that teleport". Does the API expect a true or false? (1 or 0)

As you're saying this is refering to varpbits on openOSRS and runelite
```
List<IntPair> settings = Stream.of(10, 11, 17, 32, 63, 68, 71, 101, 111, 116, 131, 144, 145, 150, 165, 176,
            179, 212, 273, 299, 302, 307, 314, 335, 347, 351,
 365, 371, 387, 399, 425, 437, 440, 
482, 622, 655, 671, 705, 794, 810,
            869, 896, 964, 970, 1630, 1671, 1672)
.map(value -> new IntPair(value, Game.getSetting(value))).distinct().collect(Collectors.toList());
```

Is this then also varpbit? or is they varbit
```
 List<IntPair> varbit = Arrays.stream(new int[]{
            192,
            199,
            357,
            2310,
            2328,
            3534,
            3741,
            4538,
            4566,
            4885,
            4895,
            4897,
            5087,
            5088,
            5089,
            5090,
            5810,
            6104,
            7255,
            9016
        })
                .mapToObj(value -> new IntPair(value, RSVarBit.get(value).getValue())).distinct().collect(
				        Collectors.toList());
```

Correct me if I'm wrong. Varpbits can contain multiple values for a specific thing, where varbit only stores one value. So in a sense varbit are derived by varpbits correct? Just so we're speaking the same language

**Comment by FALSkills** [comment] 2022-01-09 21:38
I don't have a resource that can give you which specific setting or varbit listed above goes with which area/obstacle in the game.  I can look them up individually but I don't plan on doing so.

> Also, what is the expected value for a "account got access to that teleport". Does the API expect a true or false? (1 or 0)

I'm not sure what you mean for that.  Teleports are not handled by the path generator, each teleport is detailed via the [Teleport](https://github.com/itsdax/Runescape-Web-Walker-Engine/blob/master/src/main/java/dax/teleports/Teleport.java) class, which is utilized in the DaxWalker class under the getPathTeleports and getBankPathTeleports functions.

The expected varbits/setting values are unique to each varbit/setting.  Sometimes it's 0 or 1, other times it's a value based upon quest completion which varies wildly.

> As you're saying this is refering to varpbits on openOSRS and runelite

Those are called Settings in TRiBot, varps in openosrs I believe.

> Is this then also varpbit? or is they varbit

Those are varbits.

> Correct me if I'm wrong. Varpbits can contain multiple values for a specific thing, where varbit only stores one value. So in a sense varbit are derived by varpbits correct? Just so we're speaking the same language

This is correct, the cache stores info for varbits that tells you which varp they are associated with, the starting left bit, and the ending right bit.  Using that info, you can apply bitmasks/bitshifts to acquire the desired value.

**Comment by Syhler** [comment] 2022-01-10 17:57
> I can look them up individually but I don't plan on doing so.

How do you look up a varbit? if you care to explain.
It's hard to find any information about this 😅 

> I'm not sure what you mean for that. Teleports are not handled by the path generator, each teleport is detailed via the Teleport class, which is utilized in the DaxWalker class under the getPathTeleports and getBankPathTeleports functions.

I might have misused the word "Teleport". I was referring to spirit trees or fairy rings. I assume that the API generates the path using these "teleportation devices" if the correct value from a specify varpbit/varbit is returned. correct?

**Comment by FALSkills** [comment] 2022-01-10 18:32
I can look up the varbits because they have already been added as requirements for specific paths/nodes on our web walker, and I usually add comments as to what they are for.  I can also reasonably guess what it is tied to based up on the location and my knowledge of the osrs game.  There is no real way to look up varbits other than changing things in game and reviewing the values that are modified.  Some users/clients have catalogued those changes and stored them as constants, but only Jagex really has the master list as far as I'm aware.

The spirit tree or fairy rings are classified as "DISCONNECTED_PATH", meaning they are path connections that modify start/end tiles in ways other than being a tile next to it, such as up a floor or across a body of water.  They are validated on the backend based upon varbit/settings that are included in the api call. 

I'm going to close this issue as this is unrelated to any issues with the walker itself.  Any further questions and you can find me in TRiBot discord.

**Closed by FALSkills** 2022-01-10 18:32 UTC
